# Generated by Django 4.0 on 2024-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseOneConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.TextField(max_length=25)),
                ('session_id', models.TextField(max_length=25)),
                ('study_id', models.TextField(max_length=25)),
                ('index', models.FloatField()),
                ('one_confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhaseOneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.TextField(max_length=25)),
                ('session_id', models.TextField(max_length=25)),
                ('study_id', models.TextField(max_length=25)),
                ('index', models.FloatField()),
                ('event_type', models.TextField(max_length=25)),
                ('block_type', models.FloatField()),
                ('block', models.FloatField()),
                ('trial_label', models.FloatField()),
                ('coherence', models.FloatField()),
                ('dot_correct', models.FloatField()),
                ('direction', models.FloatField()),
                ('key_press', models.FloatField()),
                ('dot_rt', models.FloatField()),
                ('word', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTwoConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.TextField(max_length=25)),
                ('session_id', models.TextField(max_length=25)),
                ('study_id', models.TextField(max_length=25)),
                ('index', models.FloatField()),
                ('two_confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTwoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.TextField(max_length=25)),
                ('session_id', models.TextField(max_length=25)),
                ('study_id', models.TextField(max_length=25)),
                ('index', models.FloatField()),
                ('event_type', models.TextField(max_length=25)),
                ('block_type', models.FloatField()),
                ('block', models.FloatField()),
                ('trial_label', models.FloatField()),
                ('coherence', models.FloatField()),
                ('dot_correct', models.FloatField()),
                ('direction', models.FloatField()),
                ('key_press', models.FloatField()),
                ('dot_rt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTwoRepeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.TextField(max_length=25)),
                ('session_id', models.TextField(max_length=25)),
                ('study_id', models.TextField(max_length=25)),
                ('index', models.FloatField()),
                ('repeat', models.FloatField()),
                ('repeat_rt', models.FloatField()),
                ('word', models.TextField(max_length=25)),
                ('word_correct', models.FloatField()),
                ('word_rt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QuesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.TextField(max_length=25)),
                ('session_id', models.TextField(max_length=25)),
                ('study_id', models.TextField(max_length=25)),
                ('ques_name', models.TextField(max_length=100)),
                ('item_no', models.FloatField()),
                ('response', models.FloatField()),
            ],
        ),
    ]
